//
// automatically generated by spin2cpp v3.6.4 on Thu Mar  8 17:13:03 2018
// /home/volsungasaga/Downloads/spin2cpp/build/spin2cpp --gas --side MainFinal (PST_Control).spin 
//

#ifndef FullDuplexSerial_Class_Defined__
#define FullDuplexSerial_Class_Defined__

#include <stdint.h>

class FullDuplexSerial {
public:
// unix end of line
#define FULLDUPLEXSERIAL_EOL (10)
  int32_t 	start(int32_t rxpin, int32_t txpin, int32_t mode, int32_t baudrate);
  void 	stop(void);
  void 	txflush(void);
  void 	rxflush(void);
  int32_t 	rxcheck(void);
  int32_t 	rxready(void);
  int32_t 	rxtime(int32_t ms);
  int32_t 	rx(void);
  void 	tx(int32_t txbyte);
  void 	str(int32_t stringptr);
  int32_t 	dec(int32_t value);
  void 	hex(int32_t value, int32_t digits);
  void 	bin(int32_t value, int32_t digits);
private:
// cog flag/id
  volatile int32_t 	cog;
// 9 contiguous longs
  volatile int32_t 	rx_head;
  volatile int32_t 	rx_tail;
  volatile int32_t 	tx_head;
  volatile int32_t 	tx_tail;
  volatile int32_t 	rx_pin;
  volatile int32_t 	tx_pin;
  volatile int32_t 	rxtx_mode;
  volatile int32_t 	bit_ticks;
  volatile int32_t 	buffer_ptr;
// transmit and receive buffers
  volatile char 	rx_buffer[16];
  volatile char 	tx_buffer[16];
  volatile char 	txlock;
  volatile char 	strlock;
};

#endif
